# Generated by Django 2.2.7 on 2019-11-08 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('article_details', models.TextField()),
                ('article_image', models.ImageField(blank=True, upload_to='static/images/articles')),
                ('article_category', models.CharField(max_length=100)),
                ('publish_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=250)),
                ('project_image', models.ImageField(upload_to='static/images/educations')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educations_name', models.CharField(max_length=250)),
                ('instituet_name', models.CharField(max_length=250)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('cartificate_image', models.ImageField(blank=True, upload_to='static/images/educations')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('why_interested', models.TextField()),
                ('interested_thinks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomender_name', models.CharField(max_length=250)),
                ('recomender_position', models.CharField(max_length=250)),
                ('recomender_url', models.URLField(blank=True, unique=True)),
                ('recomender_mail', models.EmailField(max_length=254, unique=True)),
                ('recomender_say', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=250)),
                ('skill_icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('greatings', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/author')),
                ('location', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('fb_link', models.URLField(blank=True, max_length=250)),
                ('twitter_link', models.URLField(blank=True, max_length=250)),
                ('linkedin_link', models.URLField(blank=True, max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
